kubeclt apply -f mysql-secret.yaml
kubeclt apply -f sc.yaml
kubeclt apply -f mysql-pv.yaml
kubeclt apply -f mysql-vol.yaml
kubeclt apply -f mysql.yaml
kubeclt apply -f mysql-service.yaml
kubeclt apply -f wordpress-pv.yaml
kubeclt apply -f vp-volume.yaml
kubeclt apply -f wp.yaml
kubeclt apply -f wp-service.yaml